"""
Square Multi-Colour Image Reconstructor GUI
-------------------------------------------

Purpose:
- Reconstructs square RGB images from rgb.txt or hex.txt
- Accepts files generated by the Square Multi-Colour Image Analyzer
- Displays the reconstructed image
- Saves the reconstructed image as reconstructed_image.png

Supported input formats:

rgb.txt:
    0: rgb(255, 0, 0)
    1: rgb(0, 255, 0)

hex.txt:
    0: #FF0000
    1: #00FF00

Dependencies:
    pip install pillow
"""

import os
import re
import math
import threading
import tkinter as tk
from tkinter import filedialog, messagebox
from PIL import Image, ImageTk


RGB_PATTERN = re.compile(
    r"^\s*(\d+)\s*:\s*rgb\s*\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)\s*$",
    re.IGNORECASE
)

HEX_PATTERN = re.compile(
    r"^\s*(\d+)\s*:\s*#?([0-9a-fA-F]{6})\s*$"
)


class SquareColourImageReconstructorGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Square Multi-Colour Image Reconstructor")
        self.root.geometry("900x700")
        self.root.minsize(700, 500)

        self.input_path = None
        self.output_path = None
        self.tk_image = None

        self.build_ui()

    def build_ui(self):
        self.main_frame = tk.Frame(self.root, padx=12, pady=12)
        self.main_frame.pack(fill=tk.BOTH, expand=True)

        self.title_label = tk.Label(
            self.main_frame,
            text="Square Multi-Colour Image Reconstructor",
            font=("Segoe UI", 18, "bold")
        )
        self.title_label.pack(anchor="w")

        self.button_frame = tk.Frame(self.main_frame)
        self.button_frame.pack(fill=tk.X, pady=(12, 8))

        self.open_button = tk.Button(
            self.button_frame,
            text="Open rgb.txt or hex.txt",
            command=self.open_value_file,
            height=2
        )
        self.open_button.pack(side=tk.LEFT)

        self.status_label = tk.Label(
            self.button_frame,
            text="Ready",
            anchor="w"
        )
        self.status_label.pack(side=tk.LEFT, padx=16)

        self.input_label = tk.Label(
            self.main_frame,
            text="Input file path: None",
            anchor="w",
            justify=tk.LEFT,
            wraplength=850
        )
        self.input_label.pack(fill=tk.X, pady=(4, 4))

        self.output_label = tk.Label(
            self.main_frame,
            text="Output image path: None",
            anchor="w",
            justify=tk.LEFT,
            wraplength=850
        )
        self.output_label.pack(fill=tk.X, pady=(4, 10))

        self.canvas_frame = tk.Frame(self.main_frame, bd=1, relief=tk.SUNKEN)
        self.canvas_frame.pack(fill=tk.BOTH, expand=True)

        self.canvas = tk.Canvas(self.canvas_frame, bg="#202020")
        self.canvas.pack(fill=tk.BOTH, expand=True)

    def open_value_file(self):
        path = filedialog.askopenfilename(
            title="Select rgb.txt or hex.txt",
            filetypes=[
                ("Text files", "*.txt"),
                ("All files", "*.*")
            ]
        )

        if not path:
            return

        self.input_path = path
        self.set_busy(True)
        self.status_label.config(text="Reconstructing image...")

        worker = threading.Thread(
            target=self.reconstruct_image_thread,
            args=(path,),
            daemon=True
        )
        worker.start()

    def reconstruct_image_thread(self, path):
        try:
            result = self.reconstruct_image(path)
            self.root.after(0, lambda: self.display_result(result))

        except Exception as error:
            self.root.after(0, lambda: self.handle_error(error))

    def reconstruct_image(self, path):
        pixels = self.parse_value_file(path)

        if not pixels:
            raise ValueError("No valid pixel values were found in the selected file.")

        pixel_count = len(pixels)
        side_length = math.isqrt(pixel_count)

        if side_length * side_length != pixel_count:
            raise ValueError(
                f"The number of pixels is not a perfect square. "
                f"Detected pixel count: {pixel_count}"
            )

        image = Image.new("RGB", (side_length, side_length))
        image.putdata(pixels)

        directory = os.path.dirname(path)
        output_path = os.path.join(directory, "reconstructed_image.png")

        image.save(output_path)

        return {
            "input_path": path,
            "output_path": output_path,
            "image": image,
            "size": image.size,
            "pixel_count": pixel_count
        }

    def parse_value_file(self, path):
        indexed_pixels = []

        with open(path, "r", encoding="utf-8") as file:
            for line_number, line in enumerate(file, start=1):
                stripped = line.strip()

                if not stripped:
                    continue

                rgb_match = RGB_PATTERN.match(stripped)
                hex_match = HEX_PATTERN.match(stripped)

                if rgb_match:
                    index = int(rgb_match.group(1))
                    r = int(rgb_match.group(2))
                    g = int(rgb_match.group(3))
                    b = int(rgb_match.group(4))

                    self.validate_rgb_value(r, g, b, line_number)

                    indexed_pixels.append((index, (r, g, b)))

                elif hex_match:
                    index = int(hex_match.group(1))
                    hex_value = hex_match.group(2)

                    r = int(hex_value[0:2], 16)
                    g = int(hex_value[2:4], 16)
                    b = int(hex_value[4:6], 16)

                    indexed_pixels.append((index, (r, g, b)))

                else:
                    raise ValueError(
                        f"Invalid line format at line {line_number}:\n{stripped}"
                    )

        indexed_pixels.sort(key=lambda item: item[0])

        self.validate_index_sequence(indexed_pixels)

        return [pixel for _, pixel in indexed_pixels]

    def validate_rgb_value(self, r, g, b, line_number):
        for name, value in [("R", r), ("G", g), ("B", b)]:
            if value < 0 or value > 255:
                raise ValueError(
                    f"Invalid {name} value at line {line_number}: {value}. "
                    f"RGB values must be between 0 and 255."
                )

    def validate_index_sequence(self, indexed_pixels):
        if not indexed_pixels:
            return

        expected_index = 0

        for actual_index, _ in indexed_pixels:
            if actual_index != expected_index:
                raise ValueError(
                    f"Invalid pixel index sequence. "
                    f"Expected index {expected_index}, found index {actual_index}."
                )

            expected_index += 1

    def display_result(self, result):
        display_image = result["image"].copy()
        display_image.thumbnail((760, 480), Image.Resampling.LANCZOS)

        self.tk_image = ImageTk.PhotoImage(display_image)

        self.canvas.delete("all")

        canvas_width = self.canvas.winfo_width()
        canvas_height = self.canvas.winfo_height()

        if canvas_width <= 1:
            canvas_width = 760

        if canvas_height <= 1:
            canvas_height = 480

        x = canvas_width // 2
        y = canvas_height // 2

        self.canvas.create_image(x, y, image=self.tk_image, anchor=tk.CENTER)

        width, height = result["size"]

        self.input_label.config(
            text=f"Input file path: {result['input_path']}"
        )

        self.output_label.config(
            text=f"Output image path: {result['output_path']}"
        )

        self.status_label.config(
            text=(
                f"Complete. Reconstructed image size: "
                f"{width} x {height}. "
                f"Pixels: {result['pixel_count']}"
            )
        )

        self.set_busy(False)

    def handle_error(self, error):
        self.set_busy(False)
        self.status_label.config(text="Error")
        messagebox.showerror("Reconstruction Error", str(error))

    def set_busy(self, busy):
        if busy:
            self.open_button.config(state=tk.DISABLED)
            self.root.config(cursor="watch")
        else:
            self.open_button.config(state=tk.NORMAL)
            self.root.config(cursor="")


def main():
    root = tk.Tk()
    app = SquareColourImageReconstructorGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
