#!/usr/bin/env python3
"""
compose.py

Local companion tool for the TR Tensor application.

compose.py consumes formatted output from format_paste.py, then renders custom
text/code files or Tensor-compatible files programmatically. Rendering is driven
by a user-authored JSON compose configuration file.

Input formats:
  auto, tensor_text, databank_text, json_workspace, json_records, csv_records,
  jsonl, markdown, dot

Output formats:
  custom, tensor_text, databank_text, json_workspace, json_records,
  csv_records, jsonl, markdown, summary, dot

The "custom" output format uses templates with fields such as:
  {ref}, {value}, {category}, {bank}, {register}, {address}, {ordinal},
  {meta.key}, {meta.parent_key}, {bank_title}, {json}

The pointer-target source mode lets a compose config reuse the systematic
pointer entries generated by format_paste.py. This is useful for rebuilding code
blocks from code_line entries, stitching paragraphs from sentence entries, or
generating entirely new files from category-index pointer batches.
"""

from __future__ import annotations

import argparse
import copy
import csv
import importlib.util
import io
import json
import re
import shlex
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


TOOL_DIR = Path(__file__).resolve().parent
TENSOR_SPEC_PATH = TOOL_DIR / "spec" / "tensor.py"
DEFAULT_TENSOR_CONFIG_PATH = TOOL_DIR / "spec" / "config-id.json"

if str(TOOL_DIR) not in sys.path:
    sys.path.insert(0, str(TOOL_DIR))

try:
    from format_paste import (  # type: ignore[import-not-found]  # noqa: E402
        DEFAULT_TENSOR_CONFIG,
        Bank,
        Entry,
        Workspace,
        canonical_id,
        load_tensor_config,
        natural_id_key,
        render_workspace,
    )
except ModuleNotFoundError as exc:
    if exc.name != "format_paste":
        raise
    fallback_path = TOOL_DIR / "23.py"
    fallback_spec = importlib.util.spec_from_file_location("format_paste", fallback_path)
    if fallback_spec is None or fallback_spec.loader is None:
        raise
    fallback_module = importlib.util.module_from_spec(fallback_spec)
    sys.modules["format_paste"] = fallback_module
    fallback_spec.loader.exec_module(fallback_module)
    DEFAULT_TENSOR_CONFIG = fallback_module.DEFAULT_TENSOR_CONFIG
    Bank = fallback_module.Bank
    Entry = fallback_module.Entry
    Workspace = fallback_module.Workspace
    canonical_id = fallback_module.canonical_id
    load_tensor_config = fallback_module.load_tensor_config
    natural_id_key = fallback_module.natural_id_key
    render_workspace = fallback_module.render_workspace


INPUT_FORMATS = {
    "auto",
    "tensor_text",
    "databank_text",
    "json_workspace",
    "json_records",
    "csv_records",
    "jsonl",
    "markdown",
    "dot",
}

OUTPUT_FORMATS = {
    "custom",
    "tensor_text",
    "databank_text",
    "json_workspace",
    "json_records",
    "csv_records",
    "jsonl",
    "markdown",
    "summary",
    "dot",
}


DEFAULT_COMPOSE_CONFIG: Dict[str, Any] = {
    "compose_id": "compose-default-v1",
    "description": "Default Tensor compose configuration: render selected entries as plain text.",
    "input": {
        "format": "auto",
        "merge_mode": "replace",
        "dedupe": {
            "enabled": True,
            "conflict_strategy": "next_free_address",
            "value_normalization": "exact"
        },
        "category_registers": {
            "1": "document",
            "10": "paragraph",
            "20": "sentence",
            "30": "word",
            "40": "line",
            "50": "code_block",
            "60": "code_line",
            "70": "heading",
            "80": "list_item",
            "900": "pointer"
        },
    },
    "source": {
        "mode": "entries",
        "filters": {
            "categories": [],
            "exclude_categories": ["pointer"],
            "registers": [],
            "refs": [],
            "value_regex": "",
            "meta_equals": {},
        },
        "pointer": {
            "relation": "",
            "pointer_rule": "",
            "source_ref": "",
            "source_category": "",
            "target_category": "",
            "unique": False,
        },
        "dedupe": True,
        "order_by": ["bank", "register", "address"],
    },
    "transforms": [],
    "template": {
        "header": "",
        "entry": "{value}",
        "join": "\n",
        "footer": "\n",
        "empty": "",
        "group_by": "",
        "group_header": "",
        "group_footer": "",
        "group_separator": "",
    },
    "outputs": [
        {
            "path": "",
            "format": "custom",
            "source": {},
            "transforms": [],
            "template": {},
        }
    ],
    "plugins": [],
}


@dataclass
class PointerInfo:
    relation: str = ""
    source_ref: str = ""
    target_refs: List[str] = None  # type: ignore[assignment]
    target_category: str = ""
    pointer_rule: str = ""

    def __post_init__(self) -> None:
        if self.target_refs is None:
            self.target_refs = []


def deep_merge(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    result = copy.deepcopy(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def parse_json_value(text: str) -> Any:
    text = text.strip()
    if text == "":
        return ""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return text


def set_path(obj: Dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    cur: Dict[str, Any] = obj
    for part in parts[:-1]:
        if part not in cur or not isinstance(cur[part], dict):
            cur[part] = {}
        cur = cur[part]
    cur[parts[-1]] = value


def get_path(obj: Any, dotted: str, default: Any = None) -> Any:
    cur = obj
    for part in dotted.split("."):
        if isinstance(cur, dict):
            if part not in cur:
                return default
            cur = cur[part]
        else:
            if not hasattr(cur, part):
                return default
            cur = getattr(cur, part)
    return cur


def load_compose_config(path: Optional[Path]) -> Dict[str, Any]:
    config = copy.deepcopy(DEFAULT_COMPOSE_CONFIG)
    if path:
        config = deep_merge(config, load_json(path))
    return config


def load_tensor_spec_module() -> Any:
    module_name = "tensor_spec_module"
    if module_name in sys.modules:
        return sys.modules[module_name]
    spec = importlib.util.spec_from_file_location(module_name, TENSOR_SPEC_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to import Tensor parser from {TENSOR_SPEC_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def workspace_from_dict(data: Dict[str, Any]) -> Workspace:
    workspace = Workspace()
    workspace.current_bank_id = data.get("current_bank_id")
    for bank_key, bank_data in (data.get("banks", {}) or {}).items():
        if isinstance(bank_data, dict) and "registers" in bank_data:
            bank_id = str(bank_data.get("id", bank_key))
            bank = Bank(id=bank_id, title=str(bank_data.get("title", "")), raw_id=bank_data.get("raw_id"))
            bank.meta = bank_data.get("meta", {}) or {}
            for register_id, address_map in (bank_data.get("registers", {}) or {}).items():
                for address_id, value_obj in (address_map or {}).items():
                    if isinstance(value_obj, dict) and "value" in value_obj:
                        entry = Entry(
                            bank=bank.id,
                            register=str(register_id),
                            address=str(address_id),
                            value=str(value_obj.get("value", "")),
                            raw_bank=value_obj.get("raw_bank"),
                            raw_register=value_obj.get("raw_register"),
                            raw_address=value_obj.get("raw_address"),
                            title=bank.title,
                            meta=value_obj.get("meta", {}) or {},
                        )
                    else:
                        entry = Entry(
                            bank=bank.id,
                            register=str(register_id),
                            address=str(address_id),
                            value=str(value_obj),
                            title=bank.title,
                            meta={},
                        )
                    insert_entry_nonduplicating(bank, entry)
            workspace.banks[bank.id] = bank
        elif isinstance(bank_data, dict):
            bank = Bank(id=str(bank_key))
            for register_id, address_map in bank_data.items():
                if not isinstance(address_map, dict):
                    continue
                for address_id, value in address_map.items():
                    insert_entry_nonduplicating(
                        bank,
                        Entry(
                            bank=bank.id,
                            register=str(register_id),
                            address=str(address_id),
                            value=str(value),
                            title=bank.title,
                            meta={},
                        ),
                    )
            workspace.banks[bank.id] = bank
    if workspace.current_bank_id is None and workspace.banks:
        workspace.current_bank_id = next(iter(workspace.banks))
    return workspace


def workspace_to_dict(workspace: Workspace, include_meta: bool = True) -> Dict[str, Any]:
    return workspace.to_dict(include_meta=include_meta)


def clone_workspace(workspace: Workspace) -> Workspace:
    return workspace_from_dict(workspace_to_dict(workspace, include_meta=True))


def normalize_dedupe_value(value: str, mode: str = "exact") -> str:
    text = str(value)
    if mode == "whitespace":
        return " ".join(text.split())
    if mode == "casefold":
        return text.casefold()
    if mode == "whitespace_casefold":
        return " ".join(text.split()).casefold()
    return text


def entry_fingerprint(entry: Entry, value_normalization: str = "exact") -> Tuple[Any, ...]:
    category = str(entry.meta.get("category", ""))
    parent = str(entry.meta.get("parent_key", ""))
    key = str(entry.meta.get("key", ""))
    span = (
        entry.meta.get("start_char"),
        entry.meta.get("end_char"),
        entry.meta.get("start_line"),
        entry.meta.get("end_line"),
    )
    value = normalize_dedupe_value(entry.value, value_normalization)
    if category == "pointer":
        return (
            "pointer",
            entry.meta.get("pointer_rule", ""),
            entry.meta.get("mode", ""),
            entry.meta.get("source_ref", ""),
            tuple(entry.meta.get("target_refs", []) or []),
            value,
        )
    return (category, parent, key, span, value)


def next_free_address(register_map: Dict[str, Entry], preferred: str) -> Tuple[str, str]:
    try:
        probe = int(str(preferred), 10)
    except ValueError:
        probe = max([int(address) for address in register_map if str(address).isdigit()] or [0])
    while True:
        probe += 1
        candidate = str(probe)
        if candidate not in register_map:
            return candidate, str(probe)


def insert_entry_nonduplicating(bank: Bank, entry: Entry, value_normalization: str = "exact") -> bool:
    register_map = bank.registers.setdefault(entry.register, {})
    existing = register_map.get(entry.address)
    fingerprint = entry_fingerprint(entry, value_normalization=value_normalization)
    if existing is not None:
        if entry_fingerprint(existing, value_normalization=value_normalization) == fingerprint:
            return False
        original_ref = f"{entry.bank}.{entry.register}.{entry.address}"
        entry.address, entry.raw_address = next_free_address(register_map, entry.address)
        entry.meta.setdefault("dedupe_conflict_original_ref", original_ref)
    entry.meta.setdefault("entry_fingerprint", "|".join(str(part) for part in fingerprint))
    register_map[entry.address] = entry
    return True


def dedupe_entry_sequence(entries: Sequence[Entry], value_normalization: str = "exact") -> List[Entry]:
    seen: set[Tuple[Any, ...]] = set()
    out: List[Entry] = []
    for entry in entries:
        ref_key = (entry.bank, entry.register, entry.address)
        fingerprint = entry_fingerprint(entry, value_normalization=value_normalization)
        key = (ref_key, fingerprint)
        if key in seen:
            continue
        seen.add(key)
        out.append(entry)
    return out


def detect_input_format(text: str, path: Optional[Path] = None) -> str:
    stripped = text.lstrip()
    suffix = path.suffix.lower() if path else ""
    if stripped.startswith("{") or stripped.startswith("["):
        try:
            data = json.loads(text)
            if isinstance(data, dict) and (data.get("type") == "tensor-workspace-v1" or "banks" in data):
                return "json_workspace"
            return "json_records"
        except Exception:
            pass
    non_empty = [line for line in text.splitlines() if line.strip()]
    if non_empty and all(line.lstrip().startswith("{") for line in non_empty[: min(5, len(non_empty))]):
        return "jsonl"
    if suffix == ".csv" or (non_empty and "," in non_empty[0] and "bank" in non_empty[0].lower() and "value" in non_empty[0].lower()):
        return "csv_records"
    if non_empty and non_empty[0].strip().startswith("|") and "ref" in non_empty[0].lower():
        return "markdown"
    if stripped.startswith("digraph"):
        return "dot"
    if re.search(r"^\s*[xX]?[0-9A-Za-z]+\s*\([^)]*\)\s*\{\s*$", text, flags=re.MULTILINE):
        return "tensor_text"
    return "databank_text"


def load_workspace_from_text(text: str, input_format: str, tensor_config: Dict[str, Any],
                             source: str = "<text>") -> Workspace:
    fmt = detect_input_format(text, Path(source) if source != "<text>" else None) if input_format == "auto" else input_format
    if fmt == "json_workspace":
        return workspace_from_dict(json.loads(text))
    if fmt == "json_records":
        return workspace_from_records(json.loads(text), tensor_config)
    if fmt == "csv_records":
        return workspace_from_csv(text, tensor_config)
    if fmt == "jsonl":
        records = [json.loads(line) for line in text.splitlines() if line.strip()]
        return workspace_from_records(records, tensor_config)
    if fmt == "markdown":
        return workspace_from_markdown(text, tensor_config)
    if fmt == "dot":
        return workspace_from_dot(text, tensor_config)
    if fmt in {"tensor_text", "databank_text"}:
        tensor_module = load_tensor_spec_module()
        parser = tensor_module.TensorParser(tensor_config)
        format_id = "tensor-block-v1" if fmt == "tensor_text" else "databank-register-v1"
        parsed = parser.parse_text(text, format_id=format_id, source=source)
        return workspace_from_dict(parsed.to_dict(include_meta=True))
    raise ValueError(f"Unsupported input format: {fmt}")


def workspace_from_records(data: Any, tensor_config: Dict[str, Any]) -> Workspace:
    records = data.get("records", []) if isinstance(data, dict) else data
    workspace = Workspace()
    if not isinstance(records, list):
        raise ValueError("json_records input must be a list or an object with a records list.")
    for index, record in enumerate(records, start=1):
        if not isinstance(record, dict):
            continue
        bank_raw = str(record.get("bank", record.get("bank_id", tensor_config.get("input", {}).get("default_bank_id", "1"))))
        register_raw = str(record.get("register", record.get("register_id", tensor_config.get("input", {}).get("default_register_id", "1"))))
        address_raw = str(record.get("address", record.get("address_id", index)))
        bank_id = canonical_id(bank_raw, tensor_config)
        register_id = canonical_id(register_raw, tensor_config)
        address_id = canonical_id(address_raw, tensor_config)
        bank = workspace.get_or_create_bank(bank_id, title=str(record.get("bank_title", record.get("title", ""))), raw_id=bank_raw)
        insert_entry_nonduplicating(
            bank,
            Entry(
                bank=bank.id,
                register=register_id,
                address=address_id,
                value=str(record.get("value", "")),
                raw_bank=bank_raw,
                raw_register=register_raw,
                raw_address=address_raw,
                title=str(record.get("title", "")),
                meta=parse_record_meta(record.get("meta", {})),
            ),
            value_normalization=str(tensor_config.get("id", {}).get("dedupe_value_normalization", "exact")),
        )
    workspace.dirty = True
    return workspace


def parse_record_meta(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return value
    if isinstance(value, str) and value.strip():
        try:
            parsed = json.loads(value)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            return {}
    return {}


def workspace_from_csv(text: str, tensor_config: Dict[str, Any]) -> Workspace:
    reader = csv.DictReader(io.StringIO(text))
    return workspace_from_records(list(reader), tensor_config)


def workspace_from_markdown(text: str, tensor_config: Dict[str, Any]) -> Workspace:
    lines = [line.strip() for line in text.splitlines() if line.strip().startswith("|")]
    rows = []
    for line in lines:
        cells = [cell.strip().replace("<br>", "\n") for cell in line.strip("|").split("|")]
        if cells and not all(set(cell) <= {"-", ":"} for cell in cells):
            rows.append(cells)
    if not rows:
        return Workspace()
    headers = [header.strip(" `").lower().replace(" ", "_") for header in rows[0]]
    records = []
    for row in rows[1:]:
        if len(row) != len(headers):
            continue
        record = {headers[index]: row[index].strip(" `") for index in range(len(headers))}
        if "category" in record:
            record["meta"] = {"category": record["category"]}
        records.append(record)
    return workspace_from_records(records, tensor_config)


def workspace_from_dot(text: str, tensor_config: Dict[str, Any]) -> Workspace:
    records = []
    node_re = re.compile(r'"(?P<ref>[^"]+)"\s*\[\s*label="(?P<label>(?:\\"|[^"])*)"\s*\]')
    for match in node_re.finditer(text):
        ref = match.group("ref")
        parts = ref.split(".")
        if len(parts) != 3:
            continue
        label = match.group("label").replace("\\n", "\n").replace('\\"', '"')
        label_parts = label.split("\n", 2)
        category = label_parts[1] if len(label_parts) > 2 else ""
        value = label_parts[2] if len(label_parts) > 2 else (label_parts[-1] if label_parts else "")
        records.append({
            "bank": parts[0],
            "register": parts[1],
            "address": parts[2],
            "value": value,
            "meta": {"category": category},
        })
    return workspace_from_records(records, tensor_config)


def merge_workspace(target: Workspace, incoming: Workspace, mode: str) -> Workspace:
    if mode == "replace":
        return clone_workspace(incoming)
    if mode != "merge":
        raise ValueError("merge_mode must be replace or merge")
    for bank_id, bank in incoming.banks.items():
        target_bank = target.get_or_create_bank(bank_id, title=bank.title, raw_id=bank.raw_id)
        for entry in bank.entries(sort=False):
            copied = copy.deepcopy(entry)
            copied.bank = target_bank.id
            insert_entry_nonduplicating(target_bank, copied)
    if incoming.current_bank_id:
        target.current_bank_id = incoming.current_bank_id
    elif target.current_bank_id is None and target.banks:
        target.current_bank_id = next(iter(target.banks))
    target.dirty = True
    return target


def infer_missing_metadata(workspace: Workspace, compose_config: Dict[str, Any],
                           tensor_config: Dict[str, Any]) -> Workspace:
    register_map = compose_config.get("input", {}).get("category_registers", {}) or {}
    canonical_map = {
        canonical_id(register, tensor_config): category
        for register, category in register_map.items()
    }
    counters: Dict[str, int] = {}
    for entry in workspace.entries(sort=True):
        if not entry.meta.get("category") and entry.register in canonical_map:
            entry.meta["category"] = canonical_map[entry.register]
        category = str(entry.meta.get("category", ""))
        if category:
            counters[category] = counters.get(category, 0) + 1
            entry.meta.setdefault("ordinal", counters[category])
            entry.meta.setdefault("key", f"{category}:{entry.meta['ordinal']}")
        if category == "pointer":
            info = parse_pointer_value(entry)
            if info.pointer_rule:
                entry.meta.setdefault("pointer_rule", info.pointer_rule)
            entry.meta.setdefault("relation", info.relation)
            entry.meta.setdefault("source_ref", info.source_ref)
            entry.meta.setdefault("target_refs", info.target_refs)
    enrich_ancestor_metadata(workspace)
    return workspace


def enrich_ancestor_metadata(workspace: Workspace) -> None:
    by_key: Dict[str, Entry] = {}
    by_ref: Dict[str, Entry] = {}
    by_category: Dict[str, List[Entry]] = {}
    for entry in workspace.entries(sort=True):
        key = entry.meta.get("key")
        if key:
            by_key[str(key)] = entry
        by_ref[entry_ref(entry)] = entry
        category = str(entry.meta.get("category", ""))
        if category:
            by_category.setdefault(category, []).append(entry)

    # Metadata-rich inputs from format_paste.py already carry parent_key. Use it
    # to write convenient ancestor fields for compose templates and grouping.
    for entry in workspace.entries(sort=True):
        cursor_key = entry.meta.get("parent_key")
        guard = 0
        while cursor_key and guard < 32:
            parent = by_key.get(str(cursor_key))
            if parent is None:
                break
            category = str(parent.meta.get("category", ""))
            if category:
                entry.meta.setdefault(f"ancestor_{category}_key", parent.meta.get("key", ""))
                entry.meta.setdefault(f"ancestor_{category}_ref", entry_ref(parent))
                entry.meta.setdefault(f"ancestor_{category}_ordinal", parent.meta.get("ordinal", ""))
            cursor_key = parent.meta.get("parent_key")
            guard += 1

    # Text-only Tensor/DataBank imports preserve register/category ordering but
    # not JSON metadata. Reconstruct the common format_paste hierarchy enough
    # for paragraph/sentence/word/code grouping.
    if any(entry.meta.get("ancestor_paragraph_key") for entry in by_category.get("word", [])):
        return

    paragraphs = by_category.get("paragraph", [])
    sentences = by_category.get("sentence", [])
    words = by_category.get("word", [])
    code_blocks = by_category.get("code_block", [])
    code_lines = by_category.get("code_line", [])

    if paragraphs and sentences:
        paragraph_index = 0
        for sentence in sentences:
            while paragraph_index < len(paragraphs) and sentence.value not in paragraphs[paragraph_index].value:
                paragraph_index += 1
            if paragraph_index < len(paragraphs):
                paragraph = paragraphs[paragraph_index]
                sentence.meta.setdefault("parent_key", paragraph.meta.get("key", ""))
                sentence.meta.setdefault("ancestor_paragraph_key", paragraph.meta.get("key", ""))
                sentence.meta.setdefault("ancestor_paragraph_ref", entry_ref(paragraph))
                sentence.meta.setdefault("ancestor_paragraph_ordinal", paragraph.meta.get("ordinal", ""))

    if sentences and words:
        sentence_word_counts = [len(re.findall(r"[A-Za-z0-9_]+(?:['-][A-Za-z0-9_]+)?", sentence.value)) for sentence in sentences]
        word_index = 0
        for sentence, count in zip(sentences, sentence_word_counts):
            for _ in range(count):
                if word_index >= len(words):
                    break
                word = words[word_index]
                word.meta.setdefault("parent_key", sentence.meta.get("key", ""))
                word.meta.setdefault("ancestor_sentence_key", sentence.meta.get("key", ""))
                word.meta.setdefault("ancestor_sentence_ref", entry_ref(sentence))
                word.meta.setdefault("ancestor_sentence_ordinal", sentence.meta.get("ordinal", ""))
                if sentence.meta.get("ancestor_paragraph_key"):
                    word.meta.setdefault("ancestor_paragraph_key", sentence.meta.get("ancestor_paragraph_key"))
                    word.meta.setdefault("ancestor_paragraph_ref", sentence.meta.get("ancestor_paragraph_ref"))
                    word.meta.setdefault("ancestor_paragraph_ordinal", sentence.meta.get("ancestor_paragraph_ordinal"))
                word_index += 1

    if code_blocks and code_lines:
        code_line_index = 0
        for block in code_blocks:
            count = len(block.value.splitlines()) if block.value else 0
            for _ in range(count):
                if code_line_index >= len(code_lines):
                    break
                code_line = code_lines[code_line_index]
                code_line.meta.setdefault("parent_key", block.meta.get("key", ""))
                code_line.meta.setdefault("ancestor_code_block_key", block.meta.get("key", ""))
                code_line.meta.setdefault("ancestor_code_block_ref", entry_ref(block))
                code_line.meta.setdefault("ancestor_code_block_ordinal", block.meta.get("ordinal", ""))
                code_line_index += 1


def all_entries(workspace: Workspace, sort: bool = True) -> List[Entry]:
    return list(workspace.entries(sort=sort))


def entry_ref(entry: Entry) -> str:
    return f"{entry.bank}.{entry.register}.{entry.address}"


def entry_context(entry: Entry, workspace: Workspace, index: int = 0, group_key: str = "") -> Dict[str, Any]:
    bank = workspace.banks.get(entry.bank)
    ref = entry_ref(entry)
    record = {
        "bank": entry.bank,
        "bank_title": bank.title if bank else "",
        "register": entry.register,
        "address": entry.address,
        "ref": ref,
        "value": entry.value,
        "title": entry.title,
        "index": index,
        "number": index + 1,
        "group_key": group_key,
        "category": entry.meta.get("category", ""),
        "key": entry.meta.get("key", ""),
        "parent_key": entry.meta.get("parent_key", ""),
        "ordinal": entry.meta.get("ordinal", ""),
        "start_line": entry.meta.get("start_line", ""),
        "end_line": entry.meta.get("end_line", ""),
        "start_char": entry.meta.get("start_char", ""),
        "end_char": entry.meta.get("end_char", ""),
        "meta": entry.meta,
    }
    record["json"] = json.dumps({
        "bank": entry.bank,
        "register": entry.register,
        "address": entry.address,
        "ref": ref,
        "value": entry.value,
        "title": entry.title,
        "meta": entry.meta,
    }, ensure_ascii=False)
    record["meta_json"] = json.dumps(entry.meta, ensure_ascii=False, sort_keys=True)
    return record


def resolve_context_path(context: Dict[str, Any], path: str) -> Any:
    if path in context:
        return context[path]
    cur: Any = context
    for part in path.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return ""
    return cur


def render_template(template: str, context: Dict[str, Any]) -> str:
    left = "\uFFF0"
    right = "\uFFF1"
    text = str(template).replace("{{", left).replace("}}", right)

    def replace(match: re.Match[str]) -> str:
        raw_name = match.group(1).strip()
        if not raw_name:
            return ""
        value = resolve_context_path(context, raw_name)
        if isinstance(value, (dict, list)):
            return json.dumps(value, ensure_ascii=False)
        return str(value)

    return re.sub(r"\{([^{}]+)\}", replace, text).replace(left, "{").replace(right, "}")


def parse_pointer_value(entry: Entry) -> PointerInfo:
    info = PointerInfo(pointer_rule=str(entry.meta.get("pointer_rule", "")))
    try:
        parts = shlex.split(entry.value)
    except ValueError:
        parts = entry.value.split()
    collecting_targets = False
    for part in parts:
        if "=" not in part:
            if collecting_targets:
                info.target_refs.append(part)
            continue
        key, value = part.split("=", 1)
        collecting_targets = False
        if key == "relation":
            info.relation = value
        elif key == "source":
            info.source_ref = value
        elif key == "targets":
            info.target_refs.extend(value.split())
            collecting_targets = True
        elif key == "target_category":
            info.target_category = value
    if not info.target_refs and "targets=" in entry.value:
        _, target_tail = entry.value.split("targets=", 1)
        info.target_refs = target_tail.strip().split()
    return info


def entry_lookup(workspace: Workspace) -> Dict[str, Entry]:
    return {entry_ref(entry): entry for entry in workspace.entries(sort=False)}


def pointer_matches(info: PointerInfo, pointer_entry: Entry, pointer_cfg: Dict[str, Any],
                    lookup: Dict[str, Entry]) -> bool:
    relation = pointer_cfg.get("relation", "")
    pointer_rule = pointer_cfg.get("pointer_rule", "")
    source_ref = pointer_cfg.get("source_ref", "")
    source_category = pointer_cfg.get("source_category", "")
    target_category = pointer_cfg.get("target_category", "")
    if relation and info.relation != relation:
        return False
    if pointer_rule and info.pointer_rule != pointer_rule:
        return False
    if source_ref and info.source_ref != source_ref:
        return False
    if source_category:
        source = lookup.get(info.source_ref)
        if source is None or source.meta.get("category") != source_category:
            return False
    if target_category:
        if info.target_category and info.target_category != target_category:
            return False
        target_entries = [lookup.get(ref) for ref in info.target_refs]
        if not any(target is not None and target.meta.get("category") == target_category for target in target_entries):
            return False
    return True


def source_entries(workspace: Workspace, source_cfg: Dict[str, Any]) -> List[Entry]:
    mode = source_cfg.get("mode", "entries")
    lookup = entry_lookup(workspace)
    if mode == "entries":
        entries = all_entries(workspace, sort=True)
    elif mode == "pointer_entries":
        pointer_cfg = source_cfg.get("pointer", {})
        entries = []
        for entry in all_entries(workspace, sort=True):
            if entry.meta.get("category") != "pointer":
                continue
            if pointer_matches(parse_pointer_value(entry), entry, pointer_cfg, lookup):
                entries.append(entry)
    elif mode == "pointer_targets":
        pointer_cfg = source_cfg.get("pointer", {})
        entries = []
        seen = set()
        unique = bool(pointer_cfg.get("unique", False))
        for pointer_entry in all_entries(workspace, sort=True):
            if pointer_entry.meta.get("category") != "pointer":
                continue
            info = parse_pointer_value(pointer_entry)
            if not pointer_matches(info, pointer_entry, pointer_cfg, lookup):
                continue
            for ref in info.target_refs:
                target = lookup.get(ref)
                if target is None:
                    continue
                target_category = pointer_cfg.get("target_category", "")
                if target_category and target.meta.get("category") != target_category:
                    continue
                if unique and ref in seen:
                    continue
                seen.add(ref)
                entries.append(target)
    elif mode == "pointer_sources":
        pointer_cfg = source_cfg.get("pointer", {})
        entries = []
        seen = set()
        for pointer_entry in all_entries(workspace, sort=True):
            if pointer_entry.meta.get("category") != "pointer":
                continue
            info = parse_pointer_value(pointer_entry)
            if not pointer_matches(info, pointer_entry, pointer_cfg, lookup):
                continue
            source = lookup.get(info.source_ref)
            if source is not None and info.source_ref not in seen:
                seen.add(info.source_ref)
                entries.append(source)
    else:
        raise ValueError(f"Unsupported source mode: {mode}")
    entries = apply_filters(entries, source_cfg.get("filters", {}))
    if source_cfg.get("dedupe", True):
        entries = dedupe_entry_sequence(entries)
    return order_entries(entries, source_cfg.get("order_by", []), preserve=(mode.startswith("pointer_") and not source_cfg.get("order_by")))


def apply_filters(entries: Sequence[Entry], filters: Dict[str, Any]) -> List[Entry]:
    categories = set(filters.get("categories") or [])
    exclude_categories = set(filters.get("exclude_categories") or [])
    registers = {str(value) for value in (filters.get("registers") or [])}
    refs = {str(value) for value in (filters.get("refs") or [])}
    value_regex = filters.get("value_regex") or ""
    value_re = re.compile(value_regex, re.MULTILINE) if value_regex else None
    meta_equals = filters.get("meta_equals") or {}
    out: List[Entry] = []
    for entry in entries:
        category = str(entry.meta.get("category", ""))
        if categories and category not in categories:
            continue
        if exclude_categories and category in exclude_categories:
            continue
        if registers and entry.register not in registers:
            continue
        if refs and entry_ref(entry) not in refs:
            continue
        if value_re and not value_re.search(entry.value):
            continue
        ok = True
        for key, expected in meta_equals.items():
            if get_path(entry.meta, key, None) != expected:
                ok = False
                break
        if ok:
            out.append(entry)
    return out


def sort_value_for_entry(entry: Entry, field: str) -> Any:
    if field == "ref":
        return entry_ref(entry)
    if field == "bank":
        return natural_id_key(entry.bank)
    if field == "register":
        return natural_id_key(entry.register)
    if field == "address":
        return natural_id_key(entry.address)
    if field == "value":
        return entry.value
    if field.startswith("meta."):
        value = get_path(entry.meta, field[5:], "")
        return natural_id_key(value) if isinstance(value, str) and value.isdigit() else value
    if hasattr(entry, field):
        return getattr(entry, field)
    return get_path(entry.meta, field, "")


def order_entries(entries: List[Entry], order_by: Any, preserve: bool = False) -> List[Entry]:
    if preserve:
        return entries
    if not order_by:
        order_by = ["bank", "register", "address"]
    if isinstance(order_by, str):
        order_by = [order_by]
    fields = []
    reverse = False
    for item in order_by:
        if isinstance(item, dict):
            fields.append(item.get("field", "ref"))
            reverse = reverse or str(item.get("direction", "asc")).lower() == "desc"
        else:
            fields.append(str(item))
    return sorted(entries, key=lambda entry: tuple(sort_value_for_entry(entry, field) for field in fields), reverse=reverse)


def transform_value(value: str, transforms: Sequence[Any]) -> str:
    current = value
    for item in transforms:
        if isinstance(item, str):
            name, args = item, {}
        elif isinstance(item, dict):
            name, args = str(item.get("op", "")), item
        else:
            continue
        if name == "trim":
            current = current.strip()
        elif name == "lstrip":
            current = current.lstrip()
        elif name == "rstrip":
            current = current.rstrip()
        elif name == "lower":
            current = current.lower()
        elif name == "upper":
            current = current.upper()
        elif name == "title":
            current = current.title()
        elif name == "prefix":
            current = str(args.get("text", "")) + current
        elif name == "suffix":
            current = current + str(args.get("text", ""))
        elif name == "replace_regex":
            pattern = str(args.get("pattern", ""))
            if pattern:
                current = re.sub(pattern, str(args.get("replacement", "")), current, flags=re.MULTILINE)
        elif name == "indent":
            text = str(args.get("text", "    "))
            current = "\n".join(text + line if line else line for line in current.splitlines())
        elif name == "wrap":
            width = int(args.get("width", 88))
            current = "\n".join(textwrap.wrap(current, width=width)) if current else current
        elif name == "code_fence":
            language = str(args.get("language", ""))
            current = f"```{language}\n{current.rstrip()}\n```"
    return current


def clone_entry_with_value(entry: Entry, value: str) -> Entry:
    copied = copy.deepcopy(entry)
    copied.value = value
    return copied


def apply_entry_transforms(entries: List[Entry], transforms: Sequence[Any]) -> List[Entry]:
    if not transforms:
        return entries
    return [clone_entry_with_value(entry, transform_value(entry.value, transforms)) for entry in entries]


def subset_workspace(workspace: Workspace, entries: Sequence[Entry]) -> Workspace:
    out = Workspace()
    for entry in entries:
        source_bank = workspace.banks.get(entry.bank)
        bank = out.get_or_create_bank(entry.bank, title=source_bank.title if source_bank else "", raw_id=source_bank.raw_id if source_bank else None)
        bank.meta = copy.deepcopy(source_bank.meta) if source_bank else {}
        insert_entry_nonduplicating(bank, copy.deepcopy(entry))
    out.current_bank_id = workspace.current_bank_id if workspace.current_bank_id in out.banks else (next(iter(out.banks)) if out.banks else None)
    out.dirty = True
    return out


def render_custom(entries: List[Entry], workspace: Workspace, output_cfg: Dict[str, Any]) -> str:
    template_cfg = deep_merge(DEFAULT_COMPOSE_CONFIG["template"], output_cfg.get("template", {}) or {})
    if not entries:
        return str(template_cfg.get("empty", ""))
    header = str(template_cfg.get("header", ""))
    footer = str(template_cfg.get("footer", ""))
    entry_template = str(template_cfg.get("entry", "{value}"))
    joiner = str(template_cfg.get("join", "\n"))
    group_by = str(template_cfg.get("group_by", ""))
    group_header = str(template_cfg.get("group_header", ""))
    group_footer = str(template_cfg.get("group_footer", ""))
    group_separator = str(template_cfg.get("group_separator", ""))
    pieces: List[str] = []
    if header:
        pieces.append(render_template(header, {"count": len(entries)}))
    if group_by:
        grouped: Dict[str, List[Entry]] = {}
        for entry in entries:
            ctx = entry_context(entry, workspace)
            key = str(resolve_context_path(ctx, group_by))
            grouped.setdefault(key, []).append(entry)
        group_chunks: List[str] = []
        group_index = 0
        for key, group_entries in grouped.items():
            group_context = {"group_key": key, "group_index": group_index, "count": len(group_entries)}
            group_pieces: List[str] = []
            if group_header:
                group_pieces.append(render_template(group_header, group_context))
            rendered_entries = []
            for index, entry in enumerate(group_entries):
                rendered_entries.append(render_template(entry_template, entry_context(entry, workspace, index=index, group_key=key)))
            group_pieces.append(joiner.join(rendered_entries))
            if group_footer:
                group_pieces.append(render_template(group_footer, group_context))
            group_chunks.append("".join(group_pieces))
            group_index += 1
        pieces.append(group_separator.join(group_chunks))
    else:
        pieces.append(joiner.join(render_template(entry_template, entry_context(entry, workspace, index=index)) for index, entry in enumerate(entries)))
    if footer:
        pieces.append(render_template(footer, {"count": len(entries)}))
    return "".join(pieces)


def render_output(workspace: Workspace, compose_config: Dict[str, Any], tensor_config: Dict[str, Any],
                  output_cfg: Dict[str, Any]) -> str:
    source_cfg = deep_merge(compose_config.get("source", {}), output_cfg.get("source", {}) or {})
    transforms = list(compose_config.get("transforms", []) or []) + list(output_cfg.get("transforms", []) or [])
    entries = apply_entry_transforms(source_entries(workspace, source_cfg), transforms)
    output_format = output_cfg.get("format", "custom")
    if output_format == "custom":
        effective_output = copy.deepcopy(output_cfg)
        effective_output["template"] = deep_merge(compose_config.get("template", {}), output_cfg.get("template", {}) or {})
        return render_custom(entries, workspace, effective_output)
    subset = subset_workspace(workspace, entries)
    return render_workspace(subset, output_format, tensor_config)


def write_text(path: str, text: str, encoding: str) -> None:
    if path:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(text, encoding=encoding)
    else:
        sys.stdout.write(text)


def run_plugins(workspace: Workspace, compose_config: Dict[str, Any], stage: str) -> Workspace:
    for plugin in compose_config.get("plugins", []) or []:
        if str(plugin.get("stage", "before_outputs")) != stage:
            continue
        plugin_path = Path(plugin.get("path", ""))
        if not plugin_path.is_absolute():
            plugin_path = Path.cwd() / plugin_path
        function_name = str(plugin.get("function", "transform_workspace"))
        spec = importlib.util.spec_from_file_location(f"compose_plugin_{plugin_path.stem}", plugin_path)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Unable to import compose plugin: {plugin_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        func = getattr(module, function_name)
        result = func(workspace_to_dict(workspace, include_meta=True), copy.deepcopy(compose_config), copy.deepcopy(plugin.get("args", {})))
        if result is not None:
            workspace = workspace_from_dict(result)
    return workspace


def load_workspace(paths: Sequence[str], input_format: str, tensor_config: Dict[str, Any], merge_mode: str) -> Workspace:
    workspace = Workspace()
    first = True
    for path_text in paths:
        path = Path(path_text)
        text = path.read_text(encoding=tensor_config.get("input", {}).get("encoding", "utf-8"))
        incoming = load_workspace_from_text(text, input_format, tensor_config, source=str(path))
        if first and merge_mode == "replace":
            workspace = incoming
        else:
            workspace = merge_workspace(workspace, incoming, "merge" if merge_mode == "merge" else "replace")
        first = False
    return workspace


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Compose custom text/code files from Tensor-compatible formatted paste files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python compose.py --input Tensor.txt --input-format tensor_text --config compose-config.json\n"
            "  python compose.py --input tensor-workspace.json --format custom --entry-template \"{value}\\n\" --output out.txt\n"
            "  python compose.py --write-default-config compose-config.json\n"
            "  python compose.py --input Tensor.txt --format tensor_text --category code_line --output code-lines.txt\n"
        ),
    )
    parser.add_argument("--input", "-i", action="append", default=[], help="Formatted input from format_paste.py. Can be repeated.")
    parser.add_argument("--input-format", choices=sorted(INPUT_FORMATS), default=None, help="Input format. Defaults to compose config input.format.")
    parser.add_argument("--config", help="compose.py JSON format-configuration file.")
    parser.add_argument("--tensor-config", help="Tensor config-id.json path.")
    parser.add_argument("--write-default-config", help="Write the default compose config JSON and exit.")
    parser.add_argument("--write-effective-config", help="Write the merged effective compose config JSON and continue.")
    parser.add_argument("--set", nargs=2, action="append", metavar=("PATH", "JSON_VALUE"), help="Set a dotted path in the compose config.")
    parser.add_argument("--output", "-o", help="Single-output path override.")
    parser.add_argument("--format", choices=sorted(OUTPUT_FORMATS), help="Single-output format override.")
    parser.add_argument("--category", action="append", help="Filter to category. Can be repeated.")
    parser.add_argument("--register", action="append", help="Filter to register. Can be repeated.")
    parser.add_argument("--ref", action="append", help="Filter to ref. Can be repeated.")
    parser.add_argument("--value-regex", help="Filter entries by value regex.")
    parser.add_argument("--source-mode", choices=["entries", "pointer_entries", "pointer_targets", "pointer_sources"], help="Source mode override.")
    parser.add_argument("--pointer-relation", help="Pointer relation filter for pointer source modes.")
    parser.add_argument("--pointer-rule", help="Pointer rule-name filter for pointer source modes.")
    parser.add_argument("--source-ref", help="Pointer source ref filter.")
    parser.add_argument("--source-category", help="Pointer source category filter.")
    parser.add_argument("--target-category", help="Pointer target category filter.")
    parser.add_argument("--entry-template", help="Single-output custom entry template.")
    parser.add_argument("--join", help="Single-output custom join string.")
    return parser


def apply_cli_overrides(compose_config: Dict[str, Any], args: argparse.Namespace) -> Dict[str, Any]:
    config = copy.deepcopy(compose_config)
    for dotted, value in args.set or []:
        set_path(config, dotted, parse_json_value(value))
    if args.input_format:
        set_path(config, "input.format", args.input_format)
    source = config.setdefault("source", {})
    filters = source.setdefault("filters", {})
    if args.category:
        filters["categories"] = args.category
        filters["exclude_categories"] = []
    if args.register:
        filters["registers"] = args.register
    if args.ref:
        filters["refs"] = args.ref
    if args.value_regex:
        filters["value_regex"] = args.value_regex
    if args.source_mode:
        source["mode"] = args.source_mode
    pointer = source.setdefault("pointer", {})
    if args.pointer_relation:
        pointer["relation"] = args.pointer_relation
    if args.pointer_rule:
        pointer["pointer_rule"] = args.pointer_rule
    if args.source_ref:
        pointer["source_ref"] = args.source_ref
    if args.source_category:
        pointer["source_category"] = args.source_category
    if args.target_category:
        pointer["target_category"] = args.target_category
    if args.output or args.format or args.entry_template or args.join is not None:
        output_cfg = copy.deepcopy(config.get("outputs", [{}])[0] if config.get("outputs") else {})
        if args.output is not None:
            output_cfg["path"] = args.output
        if args.format is not None:
            output_cfg["format"] = args.format
        template = output_cfg.setdefault("template", {})
        if args.entry_template is not None:
            template["entry"] = args.entry_template
        if args.join is not None:
            template["join"] = args.join
        config["outputs"] = [output_cfg]
    return config


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    if args.write_default_config:
        Path(args.write_default_config).write_text(json.dumps(DEFAULT_COMPOSE_CONFIG, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        return 0

    tensor_config = load_tensor_config(Path(args.tensor_config) if args.tensor_config else DEFAULT_TENSOR_CONFIG_PATH)
    compose_config = load_compose_config(Path(args.config) if args.config else None)
    compose_config = apply_cli_overrides(compose_config, args)

    if args.write_effective_config:
        Path(args.write_effective_config).write_text(json.dumps(compose_config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    if not args.input:
        raise ValueError("No input supplied. Use --input with a formatted file from format_paste.py.")

    workspace = load_workspace(
        args.input,
        input_format=compose_config.get("input", {}).get("format", "auto"),
        tensor_config=tensor_config,
        merge_mode=compose_config.get("input", {}).get("merge_mode", "replace"),
    )
    workspace = infer_missing_metadata(workspace, compose_config, tensor_config)
    workspace = run_plugins(workspace, compose_config, "before_outputs")

    outputs = compose_config.get("outputs", []) or [{"format": args.format or "custom", "path": args.output or ""}]
    encoding = tensor_config.get("output", {}).get("encoding", "utf-8")
    for output_cfg in outputs:
        rendered = render_output(workspace, compose_config, tensor_config, output_cfg)
        write_text(str(output_cfg.get("path", "")), rendered, encoding=encoding)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
